repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

- repo: local
  hooks:
  - id: make-test
    name: Run tests
    entry: make test
    language: system
    pass_filenames: false
    always_run: true
    stages: [commit]

  - id: make-lint
    name: Run linter
    entry: make lint
    language: system
    pass_filenames: false
    always_run: true
    stages: [commit]
