version: '3.8'

services:
  go-template:
    image: ${DOCKER_IMAGE_NAME:-ghcr.io/ci4rail/go-template}:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    command: ["/app"]
